name: Build Demo App Video
run-name: Build Demo App Video On Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: 💾 Checking out the repository
        uses: actions/checkout@v4
      - name: ⚙️ Setting up the MonkJs project
        uses: ./.github/actions/monkjs-set-up
        with:
          build-env: production
      - name: 📱 Building the demo app video
        run: cd apps/demo-app-video && yarn build:staging
