name: Deploy Documentation
run-name: Deploy Documentation To GitHub Pages After Merge

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
      pages: write

    steps:
      - name: 💾 Checking out the repository
        uses: actions/checkout@v4
      - name: ⚙️ Setting up the MonkJs project
        uses: ./.github/actions/monkjs-set-up
      - name: 📚 Building the documentation
        run: yarn build:documentation
      - name: 📃 Setting Up GitHub Pages
        uses: actions/configure-pages@v4.0.0
      - name: 📦 Uploading the artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: documentation/build
      - name: 🌐 Deploying the documentation
        uses: actions/deploy-pages@v4.0.5
