name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Build Packages
        run: |
          yarn
      - name: Test Build
        run: |
          cd website
          if [ -e yarn.lock ]; then
            yarn install
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run docs:build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.FUTURA_SECRET }}
      - name: Build Packages
        run: |
          yarn
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          cd website
          git config --global user.email "futura@monkvision.ai"
          git config --global user.name "Futura"
          if [ -e yarn.lock ]; then
            yarn install
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run docs:deploy
      - name: Install EnhanceDocs CLI
        uses: enhancedocs/enhancedocs-github-action@0.1.0
        with:
          # @see EnhanceDocs Secret API Key: https://docs.enhancedocs.com/security/api-keys
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}

      - name: Build Docs
        working-directory: website
        run: enhancedocs build docs

      - name: Push Docs
        working-directory: website
        # @see EnhanceDocs project set up: https://docs.enhancedocs.com/getting-started/set-up-project
        run: enhancedocs push <replace_with_project_id>
